name: Terraform Plan
description: Common steps for Terraform validation and plan
inputs:
  arm-client-id:
    description: Azure client id
    required: true
  arm-tenant-id:
    description: Azure tenant id
  environment:
    description: Environment
    required: true
  tf-root-dir:
    description: 'Terraform root directory'
    required: true
    default: ${{ github.workspace }}
  tf-paralellism:
    description: 'Terraform parallelism'
    required: false
    default: '50'
  tf-version:
    description: Terraform version
    required: true
  tflint-version:
    description: TFLint version
    required: false
    default: latest
  github-token:
    description: PAT token
    required: true
    default: ${{ github.token }}
outputs:
  plan-exitcode:
    description: "Terraform plan exitcode"
    value: ${{ steps.plan.outputs.exitcode }}
runs:
  using: composite
  steps:
  - uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: ${{ inputs.tf-version}}

  - uses: terraform-linters/setup-tflint@v2
    with:
      tflint_version: ${{ inputs.tflint-version }}
      github_token: ${{ inputs.github-token }}

  - name: Terraform init
    run: |
      terraform init  -input=false
    working-directory: ${{ inputs.tf-root-dir }}
    env:
      ARM_CLIENT_ID: ${{ inputs.arm-client-id }}
      ARM_TENANT_ID: ${{ inputs.arm-tenant-id }}
    shell: bash

  - name: Terraform validate
    run: |
      terraform validate
    working-directory: ${{ inputs.tf-root-dir }}
    shell: bash

  - name: Terraform fmt check
    run: |
      terraform fmt -check
    working-directory: ${{ inputs.tf-root-dir }}
    shell: bash

  - name: Tflint init
    run: |
      tflint --init
    working-directory: ${{ inputs.tf-root-dir }}
    shell: bash

  - name: Tflint
    run: |
      tflint
    working-directory: ${{ inputs.tf-root-dir }}
    shell: bash

  - name: Terraform plan
    id: plan
    run: |
      terraform plan \
        -input=false \
        -out=tfplan \
        -detailed-exitcode \
        -parallelism=${{ inputs.tf-paralellism }}
    continue-on-error: true
    working-directory: ${{ inputs.tf-root-dir }}
    env:
      ARM_CLIENT_ID: ${{ inputs.arm-client-id }}
      ARM_TENANT_ID: ${{ inputs.arm-tenant-id }}
      ARM_USE_OIDC: 'true'
    shell: bash

  - name: Check for plan error
    run: |
      echo "Terraform plan exit code was '1' - review previous step"
      exit 1
    if: always() && steps.plan.outputs.exitcode == '1'
    shell: bash

  - name: Terraform show
    run: |
      terraform show -json tfplan > tfplan.json
    if: steps.plan.outputs.exitcode == '2'
    working-directory: ${{ inputs.tf-root-dir }}
    shell: bash

  - name: Upload artifact
    uses: actions/upload-artifact@v3
    with:
      name: tfplan
      path: |
        ${{ github.workspace }}/tfplan*
    if: steps.plan.outputs.exitcode == '2'
